name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build -t bot-war .

    - name: Run tests
      run: docker run --rm -e API_URL=${{ vars.API_URL }} bot-war npm test

    - name: Deploy
      run: |
        docker tag bot-war m4x4w/bot-war:latest
        docker push m4x4w/bot-war:latest
